#%RAML 1.0 Trait
headers:
   x-correlation-id:
     description: A UUID which can be used to trace a transaction across multiple APIs.
     required: false
     example: "7cc64d24-f2ad-4d43-8893-fa24a0789a99"